import os
import subprocess
import psycopg2
import datetime
from typing import List, Optional, Tuple

import api  # you already have this: api.load_sql_password_from_credentials()


# ====== CONFIG ======
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
REPOS_ROOT = CURRENT_DIR+"/work/cloned_repos"  # adjust as needed
DB_NAME = "opencollective"
DB_USER = "postgres"
DB_HOST = "localhost"
DB_PASSWORD = api.load_sql_password_from_credentials()

# If True, store commit body (can be larger). If False, store subject only.
STORE_BODY = True

# Use --all to include all branches/tags history
INCLUDE_ALL_REFS = True


def run_git(repo_path: str, args: List[str]) -> str:
    """Run git command in repo_path and return stdout as text."""
    print(f"Running git command : git {' '.join(args)}")
    p = subprocess.run(
        ["git"] + args,
        cwd=repo_path,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    if p.returncode != 0:
        raise RuntimeError(f"git failed in {repo_path}: {p.stderr.strip()}")
    return p.stdout


def is_git_repo(path: str) -> bool:
    return os.path.isdir(os.path.join(path, ".git"))


def list_repos(root: str) -> List[str]:
    repos = []
    for name in os.listdir(root):
        p = os.path.join(root, name)
        if os.path.isdir(p) and is_git_repo(p):
            repos.append(p)
    return sorted(repos)


def parse_commit_block(block: str) -> Optional[dict]:
    """
    Parse one commit block generated by git log with NUL separators.
    Returns dict or None.
    """
    # We format as: <sha>\0<parents>\0<an>\0<ae>\0<at>\0<cn>\0<ce>\0<ct>\0<subject>\0<body>\0<stats>\n
    parts = block.split("\0")
    if len(parts) < 10:
        return None

    sha = parts[0].strip()
    parents = parts[1].strip()
    an = parts[2]
    ae = parts[3]
    at = parts[4].strip()
    cn = parts[5]
    ce = parts[6]
    ct = parts[7].strip()
    subject = parts[8]
    body = parts[9] if len(parts) >= 10 else ""

    stats_text = parts[10] if len(parts) >= 11 else ""
    files_changed, insertions, deletions = parse_shortstat(stats_text)

    return {
        "commit_hash": sha,
        "parent_hashes": parents,
        "author_name": an,
        "author_email": ae,
        "author_time": to_timestamp(at),
        "committer_name": cn,
        "committer_email": ce,
        "commit_time": to_timestamp(ct),
        "subject": subject,
        "body": body,
        "files_changed": files_changed,
        "insertions": insertions,
        "deletions": deletions,
    }


def to_timestamp(unix_seconds_str: str) -> Optional[datetime.datetime]:
    unix_seconds_str = unix_seconds_str.strip()
    if not unix_seconds_str:
        return None
    try:
        sec = int(unix_seconds_str)
        # store as naive timestamp in local timezone? better store UTC:
        return datetime.datetime.utcfromtimestamp(sec)
    except ValueError:
        return None


def parse_shortstat(s: str) -> Tuple[Optional[int], Optional[int], Optional[int]]:
    """
    Parse git --shortstat output (may be empty).
    Example: " 1 file changed, 10 insertions(+), 2 deletions(-)\n"
    """
    s = (s or "").strip()
    if not s:
        return (None, None, None)

    files_changed = None
    insertions = None
    deletions = None

    # very tolerant parsing
    # tokens separated by commas
    chunks = [c.strip() for c in s.split(",")]
    for c in chunks:
        if "file changed" in c or "files changed" in c:
            try:
                files_changed = int(c.split()[0])
            except Exception:
                pass
        elif "insertion" in c or "insertions" in c:
            try:
                insertions = int(c.split()[0])
            except Exception:
                pass
        elif "deletion" in c or "deletions" in c:
            try:
                deletions = int(c.split()[0])
            except Exception:
                pass

    return (files_changed, insertions, deletions)


def mine_repo_commits(repo_path: str) -> List[dict]:
    """
    Mine commits via git log.
    Use NUL separators to avoid message parsing issues.
    """
    repo_name = os.path.basename(repo_path.rstrip("\\/"))

    pretty_fields = [
        "%H",     # sha
        "%P",     # parents
        "%an",    # author name
        "%ae",    # author email
        "%at",    # author time (unix)
        "%cn",    # committer name
        "%ce",    # committer email
        "%ct",    # commit time (unix)
        "%s",     # subject
    ]
    if STORE_BODY:
        pretty_fields.append("%b")  # body

    pretty = "%x00".join(pretty_fields) + "%x00"  # end with NUL

    #--shortstatがあるほうがいいかも
    args = ["log", "--date=unix", f"--pretty=format:{pretty}"]
    if INCLUDE_ALL_REFS:
        args.insert(1, "--all")

    print(f"Running git in {repo_path} with args: {args}")
    out = run_git(repo_path, args)

    # Each commit ends with a shortstat line (maybe empty) then next commit begins.
    # We split by "\n\n" is unreliable; instead, we rebuild blocks:
    # The format ends each commit header with NUL; then shortstat line(s) follow until next header.
    commits: List[dict] = []
    print("Splitting lines...")
    lines = out.splitlines()

    current_header = None
    current_stats_lines: List[str] = []

    def flush():
        nonlocal current_header, current_stats_lines
        if current_header is None:
            return
        stats_text = "\n".join(current_stats_lines).strip()
        block = current_header + stats_text
        c = parse_commit_block(block)
        if c:
            c["repo_path"] = repo_path
            c["repo_name"] = repo_name
            commits.append(c)
        current_header = None
        current_stats_lines = []

    # Detect header lines: they contain many NULs
    for ln in lines:
        #print(f"{ln}/{lines}")
        if "\0" in ln:
            # new commit header encountered -> flush previous
            flush()
            current_header = ln
            current_stats_lines = []
        else:
            # stats lines or empty
            if current_header is not None:
                current_stats_lines.append(ln)

    flush()
    return commits


def upsert_commits(cur, commits: List[dict]) -> int:
    """
    Insert with upsert (overwrite on conflict).
    """
    if not commits:
        return 0

    sql = """
    INSERT INTO commit_history (
        repo_path, repo_name, commit_hash, parent_hashes,
        author_name, author_email, author_time,
        committer_name, committer_email, commit_time,
        subject, body,
        files_changed, insertions, deletions
    ) VALUES (
        %(repo_path)s, %(repo_name)s, %(commit_hash)s, %(parent_hashes)s,
        %(author_name)s, %(author_email)s, %(author_time)s,
        %(committer_name)s, %(committer_email)s, %(commit_time)s,
        %(subject)s, %(body)s,
        %(files_changed)s, %(insertions)s, %(deletions)s
    )
    ON CONFLICT (repo_path, commit_hash) DO UPDATE SET
        parent_hashes = EXCLUDED.parent_hashes,
        author_name = EXCLUDED.author_name,
        author_email = EXCLUDED.author_email,
        author_time = EXCLUDED.author_time,
        committer_name = EXCLUDED.committer_name,
        committer_email = EXCLUDED.committer_email,
        commit_time = EXCLUDED.commit_time,
        subject = EXCLUDED.subject,
        body = EXCLUDED.body,
        files_changed = EXCLUDED.files_changed,
        insertions = EXCLUDED.insertions,
        deletions = EXCLUDED.deletions,
        mined_at = now();
    """

    # If not storing body, keep empty string
    for c in commits:
        if not STORE_BODY:
            c["body"] = None

    cur.executemany(sql, commits)
    return len(commits)


def main():
    repos = list_repos(REPOS_ROOT)
    print(f"Found {len(repos)} repos under: {REPOS_ROOT}")

    conn = psycopg2.connect(
        host=DB_HOST,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD,
    )
    cur = conn.cursor()

    total_inserted = 0
    for i, repo_path in enumerate(repos, start=1):
        try:
            print(f"[{i}/{len(repos)}] Mining commits: {repo_path}")
            commits = mine_repo_commits(repo_path)
            print (f"inserting {len(commits)} commits...")
            inserted = upsert_commits(cur, commits)
            print("commits upserted, committing...")
            conn.commit()
            total_inserted += inserted
            print(f"  -> {inserted} commits upserted")
        except Exception as e:
            conn.rollback()
            print(f"  !! ERROR: {e}", file=os.sys.stderr)

    cur.close()
    conn.close()
    print(f"Done. Total commits upserted: {total_inserted}")


if __name__ == "__main__":
    main()
